"""Small, deterministic data selections used by PyInstaller specs.

These helpers run only while building a native sidecar.  Keeping the selection
logic in ordinary Python lets the release tests verify exactly which immutable
files are allowed into the core package.
"""

from __future__ import annotations

from pathlib import Path

from pipeline.stats import VECTOR_SPECS


def collect_core_info_datas(project_root: Path) -> list[tuple[str, str]]:
    """Return the feature-list files required by runtime statistics.

    The repository's ADNI CSV is research input, not a runtime dependency.  It
    must not be copied into every desktop installer.  Select the runtime
    contract, rather than the directory contents, so a feature list that is
    temporarily absent from a checkout cannot silently disappear from an
    installer.  PyInstaller will report a missing declared resource during a
    release build.
    """
    info_root = project_root / "info"
    feature_names = sorted(
        {
            str(spec["features"])
            for spec in VECTOR_SPECS.values()
            if isinstance(spec.get("features"), str)
        }
    )
    return [
        (str(info_root / feature_name), "info")
        for feature_name in feature_names
    ]


def collect_python_source_datas(source_root: Path, destination_root: str) -> list[tuple[str, str]]:
    """Copy source required for remote staging, excluding generated bytecode."""
    return [
        (str(path), str(Path(destination_root) / path.parent.relative_to(source_root)))
        for path in sorted(source_root.rglob("*.py"))
        if path.is_file() and "__pycache__" not in path.parts
    ]
